# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

#_player:
#    resource: "@LupoDiscgolf/Controller/PlayerController.php"
#    type:     annotation
#    prefix:   /player
    
LupoDiscgolfApi:
    resource: "@LupoDiscgolf/Resources/config/routing_api.yml"
    prefix:   /api
    type: rest

_home:
    pattern:  /
    defaults: { _controller: LupoDiscgolf:Home:index }
    
_app:
    pattern: /fgolf_stats
    defaults: { _controller: LupoDiscgolf:FgolfStats:index }
    
    